NOTE: 'your_experiment_name'
TRAIN_DATASET: ap10k
EVAL_DATASET: ap10k
AP10K_EVAL_SUBSET: intra-species # choose from `intra-species`, `cross-species`, `cross-family`
COMPUTE_GEOAWARE_METRICS: true
DENSE_OBJ: 1
PAIR_AUGMENT: true
TEST_SAMPLE: 20
EPOCH: 1
SOFT_EVAL: true
