NOTE: 'your_experiment_name'
DO_EVAL: true
EVAL_DATASET: ap10k
AP10K_EVAL_SUBSET: intra-species # choose from `intra-species`, `cross-species`, `cross-family`
LOAD: "path/to/weight" # Path to the model checkpoint
SOFT_EVAL: true
TEST_SAMPLE: 0
COMPUTE_GEOAWARE_METRICS: true
