deepspeed --master_port 25001 --num_nodes=1 --num_gpus=8 llava/train/train.py \
    --deepspeed /opt/tiger/LLaVA1.5/scripts/zero2.json \
    --model_name_or_path /mnt/bn/bohanzhainas1/Public_Models/vicuna-7b-v1.5 \
    --version plain \
    --data_path /mnt/bn/bohanzhainas1/Public_data/blip_laion_cc_sbu_558k/blip_laion_cc_sbu_558k.json\
    --image_folder /mnt/bn/bohanzhainas1/Public_data/llava_1.3_data/LLaVA-Pretrain/ \
    --vision_tower google/siglip-base-patch16-224 \
    --mm_projector_type mlp2x_gelu \
    --tune_mm_mlp_adapter True \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --bf16 True \
    --output_dir /mnt/bn/bohanzhainas1/shijiay/06-25-24_siglip_7b_vi \
    --num_train_epochs 1 \
    --per_device_train_batch_size 32 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 1 \
    --learning_rate 1e-3 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True 
